all: csc4240-program4

# C# compiler
CS = mcs

# Compiler Flags
CSFLAGS = /out:csc4240-program4.exe

csc4240-program4:
	$(CS) $(CSFLAGS) src/data.cs src/tree.cs src/main.cs
clean:
	rm csc4240-program4.exe
